Repository Arquisoft/dede_es4a, pull requests merged in 2022-03, with the labels that each got.

#62 Modelo de productos y categorías
  package-lock.json
  restapi/models/category.ts
  restapi/models/product.ts
  restapi/package-lock.json
  restapi/package.json
Labels: backend

#65 Modelo y controlador de usuario actualizados
  .gitignore
  restapi/controllers/user.ts
  restapi/models/user.ts
  restapi/package-lock.json
  restapi/package.json
Labels: backend

#67 Producto, categoría y conexión a la base de datos
  restapi/database.ts
  restapi/models/category.ts
  restapi/models/product.ts
  restapi/server.ts
Labels: backend

#68 Base de datos conectada y peticiones funcionando
  restapi/api.ts
  restapi/controllers/user.ts
  restapi/database.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
Labels: backend

#73 Actualizados rutas y controladores de usuario
  restapi/api.ts
  restapi/controllers/user.ts
  restapi/routes/user.ts
  restapi/server.ts
Labels: backend

#74 Se actualizan modelos y controladores. Creo rutas
  restapi/controllers/product.ts
  restapi/models/category.ts
  restapi/models/product.ts
  restapi/models/user.ts
  restapi/routes/product.ts
Labels: backend

#75 Arreglos menores y pruebas de uso
  restapi/api.ts
  restapi/controllers/product.ts
  restapi/models/category.ts
  restapi/models/product.ts
  restapi/routes/product.ts
Labels: backend

#76 Pruebas de rutas y corrección de errores
  restapi/controllers/user.ts
  restapi/models/user.ts
  restapi/routes/user.ts
Labels: backend

#80 Configuración de cloudinary y subida de fotos
  restapi/controllers/product.ts
Labels: backend

#82 Se añade función de eliminar fotos de Cloudinary
  restapi/controllers/product.ts
Labels: backend

#83 Pablof
  docs/03_system_scope_and_context.adoc
  docs/07_deployment_view.adoc
  docs/images/infraestructure_level1.png
  webapp/my_app/.gitignore
  webapp/my_app/README.md
  webapp/my_app/package-lock.json
  webapp/my_app/package.json
  webapp/my_app/public/favicon.ico
  webapp/my_app/public/index.html
  webapp/my_app/public/logo192.png
  webapp/my_app/public/logo512.png
  webapp/my_app/public/manifest.json
  webapp/my_app/public/robots.txt
  webapp/my_app/src/App.css
  webapp/my_app/src/App.test.tsx
  webapp/my_app/src/App.tsx
  webapp/my_app/src/index.css
  webapp/my_app/src/index.tsx
  webapp/my_app/src/logo.svg
  webapp/my_app/src/react-app-env.d.ts
  webapp/my_app/src/reportWebVitals.ts
  webapp/my_app/src/setupTests.ts
  webapp/my_app/tsconfig.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/Navbar/Navbar.tsx
  webapp/src/components/Users/Login.tsx
  webapp/src/components/Users/Register.tsx
  webapp/src/components/Users/User.ts
  webapp/src/components/Welcome.tsx
  webapp/src/index.tsx
Labels: frontend

#87 Las imagenes se guardan con public id
  restapi/controllers/product.ts
Labels: backend

#91 HotFix 3 vulnerabilities
  restapi/controllers/user.ts
Labels: backend

#92 Backend hot fix
  restapi/controllers/user.ts
Labels: backend

#108 Validadores signup
  restapi/middlewares/validators.ts
  restapi/routes/user.ts
Labels: backend

#109 Lectura de direcciones de un POD
  restapi/api.ts
  restapi/controllers/user.ts
  restapi/models/user.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/routes/user.ts
Labels: backend, solid

#115 Encriptar confirmPassword
  restapi/models/user.ts
Labels: backend

#117 Añadidas fechas y map para guardar productos
  restapi/models/order.ts
  restapi/models/product.ts
Labels: backend

#118 Validador de sesión finalizado
  restapi/controllers/product.ts
  restapi/controllers/user.ts
  restapi/middlewares/validators.ts
  restapi/models/product.ts
  restapi/package-lock.json
  restapi/routes/product.ts
  restapi/routes/user.ts
Labels: backend
