Repository Arquisoft/dede_es4a, pull requests merged in 2022-05, with the labels that each got.

#206 Cambios para deploy
  restapi/controllers/order.ts
  restapi/vars.ts
Labels: backend

#207 Cambio de estado de pedidos en metodos find
  restapi/controllers/order.ts
Labels: backend

#217 Cambios en la documentación
  .github/workflows/asw2122.yml
  docs/10_quality_scenarios.adoc
  docs/12_glossary.adoc
  restapi/Dockerfile
  restapi/controllers/order.ts
  restapi/controllers/product.ts
  restapi/controllers/user.ts
  restapi/routes/product.ts
  restapi/tests/api.test.ts
  restapi/vars.ts
  webapp/package-lock.json
Labels: documentation

#218 Actualizada documentación
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/09_design_decisions.adoc
Labels: documentation

#219 Cambios en decisiones arquitectónicas
  docs/09_design_decisions.adoc
Labels: documentation

#228 Cambio en error de status
  .github/workflows/asw2122.yml
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/07_deployment_view.adoc
  docs/09_design_decisions.adoc
  docs/12_glossary.adoc
  docs/images/05_level2.png
  docs/images/05_level3.png
  restapi/middlewares/validators.ts
  restapi/tests/api.test.ts
  webapp/package.json
  webapp/src/components/Cart/Address.tsx
  webapp/src/components/Cart/Cart.test.tsx
  webapp/src/components/Navbar/Navbar.test.tsx
  webapp/src/components/Productos/DeleteProduct.test.tsx
  webapp/src/components/Productos/ProductoDeleteItem.tsx
  webapp/src/components/Productos/Productos.test.tsx
  webapp/src/components/Productos/Productos.tsx
  webapp/src/components/Services/ProductsService.ts
  webapp/src/components/Services/UserService.ts
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/components/Users/Login.tsx
  webapp/src/components/Users/Register.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/index.css
Labels: backend

#236 Cambios documentación
  .github/workflows/asw2122.yml
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/04_solution_strategy.adoc
  docs/06_runtime_view.adoc
  webapp/src/components/Productos/ProductoDeleteItem.tsx
  webapp/src/components/Services/ProductsService.ts
Labels: documentation

#240 Cambios en los apartados 10 y 11
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
Labels: documentation

#244 Acabada documentación
  docs/03_system_scope_and_context.adoc
  docs/06_runtime_view.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
Labels: documentation

#252 Hot Fix Arreglo test
  docs/05_building_block_view.adoc
  webapp/jest.config.ts
  webapp/package.json
  webapp/src/components/Cart/Address.test.tsx
  webapp/src/components/Cart/Payment.test.tsx
  webapp/src/components/Order/Order.test.tsx
  webapp/src/components/Order/Order.tsx
  webapp/src/components/Order/Orders.tsx
  webapp/src/components/Services/OrderService.ts
  webapp/vars.ts
Labels: frontend, test
