Repository Arquisoft/dede_es4a, pull requests merged in 2022-04, with the labels that each got.

#123 Conexión a cluster para tests y nuevos test
  restapi/controllers/user.ts
  restapi/server.ts
  restapi/tests/api.test.ts
Labels: backend, test

#127 Completados test de usuario
  restapi/middlewares/validators.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/vars.ts
Labels: backend, test

#128 Test básicos de productos y PODs
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/vars.ts
Labels: backend, test

#129 Test de categorías
  restapi/routes/product.ts
  restapi/tests/api.test.ts
Labels: backend, test

#132 Documentación puntos 4 y 8
  docs/04_solution_strategy.adoc
  docs/08_concepts.adoc
Labels: documentation

#135 Documentación punto 9
  docs/09_design_decisions.adoc
  docs/12_glossary.adoc
Labels: documentation

#138 Pablof carrito
  package-lock.json
  package.json
  restapi/api.ts
  restapi/controllers/order.ts
  restapi/controllers/product.ts
  restapi/controllers/user.ts
  restapi/middlewares/validators.ts
  restapi/models/order.ts
  restapi/models/product.ts
  restapi/models/user.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/routes/order.ts
  restapi/routes/product.ts
  restapi/routes/user.ts
  restapi/server.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/vars.ts
  webapp/src/App.tsx
  webapp/src/components/AuthentificationComponents/LoggedIn.tsx
  webapp/src/components/Carrito/Carrito.tsx
  webapp/src/components/Carrito/CartItem.tsx
  webapp/src/components/Navbar/Navbar.tsx
  webapp/src/components/Productos/AniadirProducto.tsx
  webapp/src/components/Productos/ProductoItem.tsx
  webapp/src/components/Productos/Productos.tsx
  webapp/src/index.css
  webapp/src/index.tsx
Labels: frontend

#137 Punto 10 de la documentación
  docs/10_quality_scenarios.adoc
  docs/images/requisitos.drawio.png
Labels: documentation

#165 Arreglo en los tests
  restapi/controllers/user.ts
  restapi/middlewares/validators.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
Labels: backend, test

#169 Añadido estado al pedido
  restapi/controllers/order.ts
  restapi/models/order.ts
Labels: backend

#175 Cambios en la funcionalidad de orders
  restapi/controllers/order.ts
  restapi/routes/order.ts
Labels: backend

#176 Añadidos validadores a los pedidos
  restapi/routes/order.ts
Labels: backend

#177 Cambio formato json gastos de envío
  restapi/controllers/order.ts
  restapi/models/order.ts
  restapi/routes/order.ts
Labels: backend

#180 Constaseñas de test en var.ts
  restapi/tests/api.test.ts
  restapi/vars.ts
Labels: backend, test

#185 Arreglo seguridad CORS
  restapi/server.ts
Labels: backend

#190 Test de pedido y envío de correos electrónicos automáticos
  package-lock.json
  package.json
  restapi/controllers/order.ts
  restapi/controllers/user.ts
  restapi/models/order.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/routes/order.ts
  restapi/tests/api.test.ts
  restapi/vars.ts
Labels: backend, test

#195 Cambio test categorías
  restapi/controllers/order.ts
  restapi/tests/api.test.ts
Labels: backend

#199 Arreglado map productos en pedido
  restapi/controllers/order.ts
  restapi/routes/product.ts
Labels: fix, backend
